Repository similarweb/finala-helm, pull requests merged in 2020-07, with the labels that each got.

#15 Add elasticip resource
  values.yaml
Labels: enhancement, lgtm

#16 support enable/disable resources
  values.yaml
Labels: enhancement, lgtm

#18 Add ec2 volumes detection to collector configuration
  values.yaml
Labels: enhancement, lgtm

#17 Add redshift and ElasticSearch to collector's config and bump version.
  values.yaml
Labels: lgtm

#19 Add new collector configuration format.
  values.yaml
Labels: lgtm

#20 fix wrong values in yaml file.
  values.yaml
Labels: bug, lgtm

#21 New release of finala
  values.yaml
Labels: lgtm
